-- AUTO-GENERATED from src/data/lessons.ts by scripts/gen_lessons_seed.mjs
-- Seeds public.lessons. Required because completed_lessons.lesson_id has a
-- foreign key to lessons(id); without these rows, completing a lesson fails
-- with 23503 (completed_lessons_lesson_id_fkey) and progress never persists.
-- Idempotent via ON CONFLICT.
INSERT INTO public.lessons
  (id, level_id, sort_order, title, description, video_url, bible_verse, bible_ref, reflection_question, xp, type)
VALUES
  ('0-1', 0, 1, 'What Does It Mean to Be a Christian Today?', 'Christianity is not just a religion — it''s a relationship with God through Jesus Christ. In a world full of noise, being a Christian means choosing to follow Jesus and letting His love transform your life from the inside out.', 'https://www.youtube.com/embed/7hUKXnFnXe0', 'For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.', 'John 3:16', 'What does being a Christian mean to you personally?', 25, 'lesson'),
  ('0-2', 0, 2, 'Material Success vs Spiritual Purpose', 'The world tells us that happiness comes from wealth, status, and achievement. But Jesus offers something deeper — a purpose that money can''t buy and circumstances can''t take away. True fulfillment comes from knowing why you were created.', NULL, 'What good is it for someone to gain the whole world, yet forfeit their soul?', 'Mark 8:36', 'Have you ever achieved something you wanted and still felt empty?', 25, 'lesson'),
  ('0-3', 0, 3, 'What People Truly Seek in Life', 'At the deepest level, every person is searching for love, meaning, and belonging. These longings point us toward something beyond ourselves — toward the God who created us to know Him.', NULL, 'You have made us for yourself, O Lord, and our hearts are restless until they rest in you.', 'St. Augustine', 'What are you truly searching for in life?', 25, 'lesson'),
  ('0-4', 0, 4, 'What Do You Really Want for Your Life?', 'Imagine you could have anything. Which path speaks most to your heart?', NULL, NULL, NULL, NULL, 25, 'quiz'),
  ('1-1', 1, 1, 'The Plan of Salvation', 'God''s plan of salvation is simple but profound: He loves us, we''ve all fallen short, Jesus paid the price, and we receive salvation by faith. It''s a gift — not something we earn, but something we receive with open hands.', 'https://www.youtube.com/embed/OwuElfMiKBs', 'For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God.', 'Ephesians 2:8', 'How does it feel to know that salvation is a gift, not something you need to earn?', 40, 'lesson'),
  ('1-2', 1, 2, 'Who Jesus Is', 'Jesus is not just a historical figure or a good teacher — He is God in human form. He came to show us what God is like, to live a perfect life, and to give His life so we could be forgiven and made new.', NULL, 'Jesus answered, ''I am the way and the truth and the life. No one comes to the Father except through me.''', 'John 14:6', 'Before today, who did you think Jesus was?', 40, 'lesson'),
  ('1-3', 1, 3, 'What Sin Means', 'Sin isn''t just about breaking rules — it''s anything that separates us from God. It''s the gap between who we are and who God made us to be. The good news is that Jesus bridges that gap.', NULL, 'For all have sinned and fall short of the glory of God.', 'Romans 3:23', 'Is there anything in your life that you feel separates you from God?', 40, 'lesson'),
  ('1-4', 1, 4, 'What It Means to Be Born Again', 'Being born again means starting fresh — receiving a new spiritual life through Jesus. Just as you were physically born, God offers a spiritual rebirth that transforms your identity, purpose, and future.', NULL, 'Jesus replied, ''Very truly I tell you, no one can see the kingdom of God unless they are born again.''', 'John 3:3', 'What would it mean for you to start completely fresh?', 40, 'lesson'),
  ('1-5', 1, 5, 'Beginning a Relationship with God', 'A relationship with God begins with a simple conversation — prayer. You don''t need fancy words or perfect behavior. God meets you right where you are and invites you to walk with Him daily.', NULL, 'Come near to God and he will come near to you.', 'James 4:8', 'If you could say one thing to God right now, what would it be?', 40, 'lesson'),
  ('2-1', 2, 1, 'How to Pray', 'Prayer is simply talking to God. There''s no perfect formula — just honesty, gratitude, and trust. Start by telling God what''s on your heart, thanking Him for His blessings, and asking for His guidance.', NULL, 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.', 'Philippians 4:6', 'What is one thing you''d like to talk to God about today?', 50, 'lesson'),
  ('2-2', 2, 2, 'How to Read the Bible', 'The Bible is God''s letter to you. Start with small portions — a few verses a day. Read slowly, think about what it means, and ask God to help you understand. The Gospel of John is a great place to begin.', NULL, 'Your word is a lamp for my feet, a light on my path.', 'Psalm 119:105', 'Have you ever read any part of the Bible? What stood out?', 50, 'lesson'),
  ('2-3', 2, 3, 'Understanding Scripture', 'Understanding the Bible takes time and patience. Consider the context, who wrote it, and who it was written for. Let the Holy Spirit guide your reading, and don''t be afraid to ask questions.', NULL, 'All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness.', '2 Timothy 3:16', 'What question do you have about the Bible right now?', 50, 'lesson'),
  ('2-4', 2, 4, 'Creating a Spiritual Journal', 'A spiritual journal is a place to record your thoughts, prayers, and what God is teaching you. Writing helps you process your spiritual journey and notice patterns of growth and answered prayers.', NULL, 'Then the Lord replied: ''Write down the revelation and make it plain on tablets so that a herald may run with it.''', 'Habakkuk 2:2', 'What would you write in your first journal entry?', 50, 'lesson'),
  ('2-5', 2, 5, 'Listening to God', 'God speaks through His Word, through prayer, through other believers, and through the quiet voice of His Spirit. Learning to listen is one of the most beautiful parts of the Christian life.', NULL, 'Be still, and know that I am God.', 'Psalm 46:10', 'When was a time you felt a sense of peace or guidance that you couldn''t explain?', 50, 'lesson'),
  ('3-1', 3, 1, 'Facing Temptation', 'Temptation is part of life, but it doesn''t define you. Jesus Himself was tempted and overcame. Through His strength, prayer, and wisdom from Scripture, you can resist temptation and grow stronger.', NULL, 'No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear.', '1 Corinthians 10:13', 'What temptation do you find most challenging?', 60, 'lesson'),
  ('3-2', 3, 2, 'Faith in Everyday Life', 'Faith isn''t just for Sundays — it''s for Monday mornings, difficult conversations, and ordinary moments. When you bring God into every part of your day, everything becomes an opportunity to grow.', NULL, 'So whether you eat or drink or whatever you do, do it all for the glory of God.', '1 Corinthians 10:31', 'How can you include God in one ordinary moment today?', 60, 'lesson'),
  ('3-3', 3, 3, 'Family and Faith', 'Faith begins at home. Whether your family shares your beliefs or not, you can be a light through love, patience, and example. God calls us to build homes grounded in His love.', NULL, 'But as for me and my household, we will serve the Lord.', 'Joshua 24:15', 'How does your faith affect your family relationships?', 60, 'lesson'),
  ('3-4', 3, 4, 'Christian Community', 'You were never meant to walk this journey alone. Christian community — whether a small group, a church, or a few friends — provides encouragement, accountability, and a place to belong.', NULL, 'For where two or three gather in my name, there am I with them.', 'Matthew 18:20', 'Do you have people in your life who encourage your faith?', 60, 'lesson'),
  ('3-5', 3, 5, 'Sharing Your Faith', 'Sharing your faith doesn''t mean having all the answers — it means sharing what God has done in your life. Your story is powerful, and someone needs to hear it.', NULL, 'Always be prepared to give an answer to everyone who asks you to give the reason for the hope that you have.', '1 Peter 3:15', 'If someone asked you why you believe, what would you say?', 60, 'lesson')
ON CONFLICT (id) DO UPDATE SET
  level_id            = EXCLUDED.level_id,
  sort_order          = EXCLUDED.sort_order,
  title               = EXCLUDED.title,
  description         = EXCLUDED.description,
  video_url           = EXCLUDED.video_url,
  bible_verse         = EXCLUDED.bible_verse,
  bible_ref           = EXCLUDED.bible_ref,
  reflection_question = EXCLUDED.reflection_question,
  xp                  = EXCLUDED.xp,
  type                = EXCLUDED.type;
